/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Pages.customerPages;

import Business.Customer.Patient;
import Business.Database.DB4OUtil;
import Business.Departments.Organization;
import Business.EcoSystem;
import Business.Employees.Employee;
import Business.Enterprises.Enterprise;
import Business.Network.Network;
import Business.Role.CustomerRole;
import Business.UserAccount.UserAccount;
import java.awt.Color;
import java.awt.Image;
import java.awt.event.KeyEvent;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author Rohit
 */
public class Create_New_Patient extends javax.swing.JFrame {

    /**
     * Creates new form Create_New_Patient
     */
    JPanel rightPanel;
  //  Image image;
    String photoPath; 
    UserAccount patient;
    Organization organization;
    Enterprise enterprise;
    EcoSystem business;
    DB4OUtil dB4OUtil;
    public Create_New_Patient(JPanel panelRight, UserAccount patient, Organization organization, Enterprise enterprise, EcoSystem business, DB4OUtil dB4OUtil) {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
       initComponents();

        this.business = business;
        this.rightPanel = panelRight;
        this.patient = patient;
        this.organization = organization;
        this.enterprise = enterprise;
        this.patient = patient;
        this.dB4OUtil = dB4OUtil;


        populateComboBox();
        populateInitials();
    }

        public void populateComboBox(){


         DefaultComboBoxModel dm=new DefaultComboBoxModel();
         dm.addElement("Select");
           for(Network n:business.getNetworkList()){
           dm.addElement(n);
   }
           comboBoxStateNetwork.setModel(dm);
    }

        public void populateInitials(){
        lblWarningFName.setVisible(false);
        lblWarningLastName.setVisible(false);
        lblWarningPhoneNumber.setVisible(false);
        lblWarningDOB.setVisible(false);
        lblWarningEmail.setVisible(false);
        lblWarningGender.setVisible(false);
        lblWarningNetwork.setVisible(false);
        lblWarningPWD.setVisible(false);
        }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        btn_close = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblWarningFName = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txtUserId = new javax.swing.JTextField();
        lblWarningEmail = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        lblWarningDOB = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        txtMobile = new javax.swing.JTextField();
        lblWarningPhoneNumber = new javax.swing.JLabel();
        lblLastName = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblWarningPWD = new javax.swing.JLabel();
        lblLastName1 = new javax.swing.JLabel();
        rBtnMale = new javax.swing.JRadioButton();
        rBtnFemale = new javax.swing.JRadioButton();
        lblWarningGender = new javax.swing.JLabel();
        lblWarningLastName = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        comboBoxStateNetwork = new javax.swing.JComboBox<>();
        lblWarningNetwork = new javax.swing.JLabel();
        btn_Create = new java.awt.Button();
        inPhotoBtn1 = new javax.swing.JButton();
        jPhoto1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setPreferredSize(new java.awt.Dimension(1140, 510));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(96, 83, 150));
        jLabel5.setText("<html> <u>You are one step closer for hassle-free medicare!");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 160, 433, 33));

        jPanel15.setBackground(new java.awt.Color(96, 83, 150));

        btn_close.setBackground(new java.awt.Color(96, 83, 150));
        btn_close.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_close.setForeground(new java.awt.Color(255, 255, 255));
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/icons8_multiply_56px.png"))); // NOI18N
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(btn_close)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_close, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 0, -1, -1));

        jPanel11.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(-3, 86, 1370, 10));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/images/group_52px_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 26, -1, 44));

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(96, 83, 150));
        jLabel16.setText("Welcome to AAA Medicare Group!");
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 32, 310, 33));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(232, 201, 232)));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(96, 83, 150));
        jLabel10.setText("First Name");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 90, 110, 27));

        txtFirstName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtFirstNameKeyPressed(evt);
            }
        });
        jPanel2.add(txtFirstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 180, -1));

        lblWarningFName.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningFName.setText("jLabel2");
        jPanel2.add(lblWarningFName, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 120, 230, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(96, 83, 150));
        jLabel13.setText("Email");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 110, 27));
        jPanel2.add(txtUserId, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 160, 180, -1));

        lblWarningEmail.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningEmail.setText("jLabel2");
        jPanel2.add(lblWarningEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 380, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(96, 83, 150));
        jLabel14.setText("Date of birth");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 110, 27));

        jDateChooser1.setMaxSelectableDate(new java.util.Date(1586926909000L));
        jPanel2.add(jDateChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 220, 180, -1));

        lblWarningDOB.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningDOB.setText("jLabel2");
        jPanel2.add(lblWarningDOB, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 250, 240, -1));

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(96, 83, 150));
        jLabel12.setText("Contact number");
        jPanel2.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(62, 274, 110, 27));

        txtMobile.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtMobileKeyPressed(evt);
            }
        });
        jPanel2.add(txtMobile, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 280, 180, -1));

        lblWarningPhoneNumber.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningPhoneNumber.setText("numberlabel");
        jPanel2.add(lblWarningPhoneNumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 310, 470, -1));

        lblLastName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(96, 83, 150));
        lblLastName.setText("Last Name");
        jPanel2.add(lblLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 90, 80, 20));

        txtLastName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtLastNameKeyPressed(evt);
            }
        });
        jPanel2.add(txtLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 160, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(96, 83, 150));
        jLabel11.setText("Password");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 220, 80, -1));

        txtPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPasswordActionPerformed(evt);
            }
        });
        jPanel2.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 220, 160, -1));

        lblWarningPWD.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningPWD.setText("jLabel2");
        jPanel2.add(lblWarningPWD, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 250, -1, -1));

        lblLastName1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblLastName1.setForeground(new java.awt.Color(96, 83, 150));
        lblLastName1.setText("Gender");
        jPanel2.add(lblLastName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 80, 20));

        buttonGroup1.add(rBtnMale);
        rBtnMale.setText("Male");
        rBtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnMaleActionPerformed(evt);
            }
        });
        jPanel2.add(rBtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 160, -1, -1));

        buttonGroup1.add(rBtnFemale);
        rBtnFemale.setText("Female");
        jPanel2.add(rBtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 160, -1, -1));

        lblWarningGender.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningGender.setText("jLabel2");
        jPanel2.add(lblWarningGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 190, 230, -1));

        lblWarningLastName.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningLastName.setText("jLabel2");
        jPanel2.add(lblWarningLastName, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, 220, -1));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(96, 83, 150));
        jLabel17.setText("Home State");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 280, 94, -1));

        comboBoxStateNetwork.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jPanel2.add(comboBoxStateNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 280, 160, -1));

        lblWarningNetwork.setForeground(new java.awt.Color(255, 0, 0));
        lblWarningNetwork.setText("jLabel2");
        jPanel2.add(lblWarningNetwork, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 310, -1, -1));

        btn_Create.setBackground(new java.awt.Color(96, 83, 150));
        btn_Create.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btn_Create.setForeground(new java.awt.Color(255, 255, 255));
        btn_Create.setLabel("Join Now!");
        btn_Create.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_CreateActionPerformed(evt);
            }
        });
        jPanel2.add(btn_Create, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 450, 97, 35));

        inPhotoBtn1.setBackground(new java.awt.Color(96, 83, 150));
        inPhotoBtn1.setForeground(new java.awt.Color(255, 255, 255));
        inPhotoBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Pages/images/icons8-client_management.png"))); // NOI18N
        inPhotoBtn1.setText("Upload Pic");
        inPhotoBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inPhotoBtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(inPhotoBtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 380, -1, -1));
        jPanel2.add(jPhoto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 376, 50, 50));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 200, 930, 530));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1367, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 730, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btn_closeMouseClicked

        public boolean userIdFound(String email){
        int count = 0;
        for(Patient patient: business.getPatientDirectory().getUserAccountList()) {
            if( patient.getUserName().equals(email)){
                count = 1;
                break;
            }
          }

       if (count == 0)
           return false;
           else
           return true;
    }

    public boolean checkString(String string){
        Pattern p = Pattern.compile("^[A-Za-z\\s]+$");
        Matcher m = p.matcher(string);
        boolean b = m.matches();
        return b;
    }

//    public boolean checkAge(String age){
//        Pattern p = Pattern.compile("^(0?[1-9]|[1-9][0-9])$");
//        Matcher m = p.matcher(age);
//        boolean b = m.matches();
//        return b;
//    }


    public boolean checkContactNumber(String number){
        Pattern p = Pattern.compile("^[1-9]\\d{9}$");
        Matcher m = p.matcher(number);
        boolean b = m.matches();
        return b;
    }

    public boolean checkEmail(String email){
        Pattern p = Pattern.compile("^[a-zA-Z0-9]+_[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");
        Matcher m = p.matcher(email);
        boolean b = m.matches();
        return b;
    }
    private void btn_CreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_CreateActionPerformed


         Color customColor = new Color(232,201,232);

        if(txtFirstName.getText().isEmpty()){
            lblWarningFName.setVisible(true);
            lblWarningFName.setText("Cannot be empty");
//                            usrNameLabel.setForeground (Color.red);
            txtFirstName.setBorder(BorderFactory.createLineBorder(Color.RED));
        }else if (txtLastName.getText().isEmpty()){
            txtFirstName.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningFName.setVisible(false);
            lblWarningLastName.setVisible(true);
            lblWarningLastName.setText("Cannot be empty");
//                            usrNameLabel.setForeground (Color.red);
            txtLastName.setBorder(BorderFactory.createLineBorder(Color.RED));
        }

//        else if(!checkString(lastName)){
//            JOptionPane.showMessageDialog(null, "Please enter valid Last Name");
//        }
            else if(txtUserId.getText().isEmpty()){
            txtFirstName.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningFName.setVisible(false);
            txtLastName.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningLastName.setVisible(false);
            lblWarningEmail.setVisible(true);
            lblWarningEmail.setText("Username cannot be empty");
            txtUserId.setBorder(BorderFactory.createLineBorder(Color.RED));
        }

        else if(!business.getPatientDirectory().checkIfUsernameIsUnique(txtUserId.getText())){
                        txtLastName.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningLastName.setVisible(false);
            txtFirstName.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningFName.setVisible(false);
            txtUserId.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningEmail.setVisible(true);
            lblWarningEmail.setText("Username already exists. Please try another.");
            txtUserId.setBorder(BorderFactory.createLineBorder(Color.RED));
        }

        else if(!checkEmail(txtUserId.getText())){
                        txtLastName.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningLastName.setVisible(false);
            txtFirstName.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningFName.setVisible(false);
            lblWarningEmail.setVisible(false);

            txtUserId.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningEmail.setVisible(true);
            lblWarningEmail.setText("Username form should be XXX_XXX@xxx.com");
            txtUserId.setBorder(BorderFactory.createLineBorder(Color.RED));
        }
        else if(!rBtnMale.isSelected()&& !rBtnFemale.isSelected()){
                        txtLastName.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningLastName.setVisible(false);
            txtFirstName.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningFName.setVisible(false);
            lblWarningEmail.setVisible(false);
            txtUserId.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningGender.setVisible(true);
            lblWarningGender.setText("Select your gender");
//            lblWarningGender.setBorder(BorderFactory.createLineBorder(Color.RED));
        }

            else if(jDateChooser1.getDate()==null){
                            lblWarningEmail.setVisible(false);
            txtUserId.setBorder(BorderFactory.createLineBorder(Color.gray));
                            txtLastName.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningLastName.setVisible(false);
            txtFirstName.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningFName.setVisible(false);
            lblWarningGender.setVisible(false);
            lblWarningDOB.setVisible(true);
            lblWarningDOB.setText("Please select your date of birth");
            jDateChooser1.setBorder(BorderFactory.createLineBorder(Color.RED));
        }

            else if(txtPassword.getText().isEmpty()){
                lblWarningGender.setVisible(false);
                            lblWarningEmail.setVisible(false);
            txtUserId.setBorder(BorderFactory.createLineBorder(Color.gray));
                            txtLastName.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningLastName.setVisible(false);
            txtFirstName.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningFName.setVisible(false);
            lblWarningDOB.setVisible(false);
            jDateChooser1.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningPWD.setVisible(true);
            lblWarningPWD.setText("Set your password");
            txtPassword.setBorder(BorderFactory.createLineBorder(Color.RED));
        }

        else if(!checkContactNumber(txtMobile.getText())){
                        lblWarningDOB.setVisible(false);
            jDateChooser1.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningGender.setVisible(false);
                        lblWarningEmail.setVisible(false);
            txtUserId.setBorder(BorderFactory.createLineBorder(Color.gray));
                        txtLastName.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningLastName.setVisible(false);
            txtFirstName.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningFName.setVisible(false);
            lblWarningPWD.setVisible(false);
            txtPassword.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningPhoneNumber.setVisible(true);
            lblWarningPhoneNumber.setText("Please enter valid contact number. Number must be of 10 digits in the format of XXX-XXX-XXXX");
            txtMobile.setBorder(BorderFactory.createLineBorder(Color.RED));
        }

        else if(comboBoxStateNetwork.getSelectedIndex()<=0){
                        lblWarningPWD.setVisible(false);
            txtPassword.setBorder(BorderFactory.createLineBorder(Color.gray));
                        lblWarningDOB.setVisible(false);
            jDateChooser1.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningGender.setVisible(false);
                        lblWarningEmail.setVisible(false);
            txtUserId.setBorder(BorderFactory.createLineBorder(Color.gray));
                        txtLastName.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningLastName.setVisible(false);
            txtFirstName.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningFName.setVisible(false);
            lblWarningPhoneNumber.setVisible(false);
            txtMobile.setBorder(BorderFactory.createLineBorder(Color.gray));
            lblWarningNetwork.setVisible(true);
            lblWarningNetwork.setText("Please select your state");
//            lblWarningNetwork.setBorder(BorderFactory.createLineBorder(Color.RED));
        }
        else if(this.photoPath == null){
            JOptionPane.showMessageDialog(null, "Please upload your picture");
        } 

        else {

        lblWarningNetwork.setVisible(false);
        String firstName = txtFirstName.getText();
        String lastName = txtLastName.getText();
        System.out.println(" txtmobile "+txtMobile.getText());

        String contactNumber = txtMobile.getText();
            System.out.println("Phone Number"+contactNumber);
        String email = txtUserId.getText();
        String password = txtPassword.getText();
        Date date = jDateChooser1.getDate();

        Network network = (Network)comboBoxStateNetwork.getSelectedItem();
        String gender = "";


          Patient patient =  business.getPatientDirectory().createUserAccount(email, password, firstName,lastName, new CustomerRole());


          patient.setDob(date);
          patient.setMobno(txtMobile.getText());
          patient.setNetwork(network);
          patient.setProfilePicture(photoPath);

          if(rBtnMale.isSelected()){
              gender = "Male";
          }
          if(rBtnFemale.isSelected()){
              gender = "Female";
          }
          patient.setGender(gender);


         JOptionPane.showMessageDialog(null, "Congratulations! "+patient.getfName()+" "+patient.getLastName()+ " You are registered");


//          Color customColor = new Color(232,201,232);

          txtFirstName.setText("");
          txtFirstName.setBorder(BorderFactory.createLineBorder(customColor));
          txtLastName.setText("");
          txtLastName.setBorder(BorderFactory.createLineBorder(customColor));
          txtMobile.setText("");
          txtMobile.setBorder(BorderFactory.createLineBorder(customColor));
          txtPassword.setText("");
          txtPassword.setBorder(BorderFactory.createLineBorder(customColor));
          txtUserId.setText("");
          txtUserId.setBorder(BorderFactory.createLineBorder(customColor));
          rBtnFemale.setSelected(false);
          rBtnMale.setSelected(false);
          jDateChooser1.setDate(null);

          populateInitials();

          dB4OUtil.storeSystem(business);
          dispose();
          }


    }//GEN-LAST:event_btn_CreateActionPerformed

    private void rBtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnMaleActionPerformed

    private void txtLastNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLastNameKeyPressed
        // TODO add your handling code here:

        char c = evt.getKeyChar();

        if(Character.isLetter(c)||(Character.isWhitespace(c)||(Character.isISOControl(c)))){
        txtLastName.setEditable(true);
        lblWarningLastName.setVisible(false);
        lblWarningLastName.setText("");
        }else{
        txtLastName.setEditable(false);
        lblWarningLastName.setVisible(true);
        lblWarningLastName.setText("Name should contain only characters");
        }
    }//GEN-LAST:event_txtLastNameKeyPressed

    private void txtMobileKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtMobileKeyPressed
        // TODO add your handling code here:

    }//GEN-LAST:event_txtMobileKeyPressed

    private void txtFirstNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtFirstNameKeyPressed
        // TODO add your handling code here:

                char c = evt.getKeyChar();

        if(Character.isLetter(c)||(Character.isWhitespace(c)||(Character.isISOControl(c)))){
        txtFirstName.setEditable(true);
        lblWarningFName.setVisible(false);
        lblWarningFName.setText("");
        }else{
        txtFirstName.setEditable(false);
        lblWarningFName.setVisible(true);
        lblWarningFName.setText("Name should contain only characters");
        }
    }//GEN-LAST:event_txtFirstNameKeyPressed

    private void txtPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPasswordActionPerformed

    private void inPhotoBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inPhotoBtn1ActionPerformed
        // Code to upload Image: Reference - Stackoverflow.com

        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "JPG & PNG Images", "jpg","png");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(Create_New_Patient.this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println("You chose to open this file: " +
                chooser.getSelectedFile().getName());}

                this.photoPath = chooser.getSelectedFile().getPath();
                ImageIcon iconLogo = new ImageIcon(photoPath);
                jPhoto1.setIcon(iconLogo);        
        
        /*
        ImageIcon icon = new ImageIcon(chooser.getSelectedFile().getPath());
        image = icon.getImage();
        Image newimg = image.getScaledInstance(70,70,Image.SCALE_SMOOTH);
        ImageIcon icon2 = new ImageIcon(newimg);
        jPhoto1.setVisible(true);
        jPhoto1.setIcon(icon2);   */

    }//GEN-LAST:event_inPhotoBtn1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btn_Create;
    private javax.swing.JLabel btn_close;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> comboBoxStateNetwork;
    private javax.swing.JButton inPhotoBtn1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jPhoto1;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblLastName1;
    private javax.swing.JLabel lblWarningDOB;
    private javax.swing.JLabel lblWarningEmail;
    private javax.swing.JLabel lblWarningFName;
    private javax.swing.JLabel lblWarningGender;
    private javax.swing.JLabel lblWarningLastName;
    private javax.swing.JLabel lblWarningNetwork;
    private javax.swing.JLabel lblWarningPWD;
    private javax.swing.JLabel lblWarningPhoneNumber;
    private javax.swing.JRadioButton rBtnFemale;
    private javax.swing.JRadioButton rBtnMale;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMobile;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUserId;
    // End of variables declaration//GEN-END:variables
}
