/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Pages.customerPages;


import Business.Customer.Appointment;
import Business.Customer.AppointmentHistory;
import Business.Customer.Customer;
import Business.Customer.Patient;
import Business.Medical.MedicalHistory;
import Business.Medical.MedicalReport;
import Business.Medical.PatientDocRecord;
import Business.Medical.PatientSurgeryRecord;
//import UI_Pages.LabAssistant.LabProcess;
import UI_Pages.MedicalHistory.MedicalDocDisplay;
import UI_Pages.MedicalHistory.MedicalReportDisplay;
import UI_Pages.MedicalHistory.MedicalSurgeryDisplay;
import java.awt.CardLayout;
import java.awt.Color;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Sudhanshu Gangele
 */
public class PatientMedicalHistory extends javax.swing.JPanel {
    
    public Patient pat1;

   
    
    JPanel rightPanel;
    public PatientMedicalHistory(JPanel rightPanel,Patient pat1) {
        this.pat1 = pat1;
        this.rightPanel = rightPanel;
        
        initComponents();
        
        init();
        
        
        
    }
    
   
    
    

    void init(){
        
    patientLabel.setText(pat1.getfName() + " " + pat1.getLastName());
    populateMedRecords();
    populateDocRecords();
        // Setting color of JTable
        
        
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.white);
       // headerRenderer.set(Color.BLACK);

        for (int i = 0; i < tblDocReports.getModel().getColumnCount(); i++) {
            tblDocReports.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }
        for (int i = 0; i < tblMedicalReports.getModel().getColumnCount(); i++) {
            tblMedicalReports.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
        }  
    
    }
    
    
    
    void populateDocRecords(){
        
        
         DefaultTableModel model1 = (DefaultTableModel) tblDocReports.getModel();
          model1.setRowCount(0);
        
        for( PatientDocRecord pDoc : pat1.getMedHist().getPatientDocDir()){

             
    

                        Object[] row = new Object[3];
                    
                        row[0] = pDoc;
//                        
//                        if(pDoc.getDate()!= null){
//                        Format f = new SimpleDateFormat("MM/dd/yy");
//                        String strDate = f.format(pDoc.getDate());
//                        row[1] = strDate;
//                        }
                        String helloWorld = pDoc.getDate();
                        String hellWrld = helloWorld.replace(" 00:00:00 EST "," ");
                        row[1] = hellWrld;
                        //row[2] = pDoc;
                        
                        

                        model1.addRow(row);
                    
          }

    
    }
    

    
    
    
    
      void populateMedRecords(){
        
     
        
        
            
        DefaultTableModel model2 = (DefaultTableModel) tblMedicalReports.getModel();
        
        model2.setRowCount(0);
        
        for( MedicalReport mRec : pat1.getMedHist().getMedReportDir()){

             
    

                        Object[] row = new Object[3];
                    
                        row[0] = mRec;
                        
                        if(mRec.getDate()!= null){
                        Format f = new SimpleDateFormat("MM/dd/yy");
                        String strDate = f.format(mRec.getDate());
                        row[1] = strDate;
                        }
                        
                       // row[1] = mRec.getDate();
                        //row[2] = pDoc;
                        
                        

                        model2.addRow(row);
                    
          }

    
    
    };
      
      
       
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblMedicalReports = new javax.swing.JTable();
        jLabel11 = new javax.swing.JLabel();
        btnViewMedReports = new java.awt.Button();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDocReports = new javax.swing.JTable();
        btnViewDocRecs = new java.awt.Button();
        jPanel15 = new javax.swing.JPanel();
        btn_close = new javax.swing.JLabel();
        patientLabel = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jScrollPane1.setBackground(new java.awt.Color(247, 247, 247));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tblMedicalReports.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblMedicalReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Test Report Number", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblMedicalReports.setGridColor(new java.awt.Color(247, 247, 247));
        tblMedicalReports.setRowHeight(20);
        tblMedicalReports.setSelectionBackground(new java.awt.Color(96, 83, 150));
        jScrollPane1.setViewportView(tblMedicalReports);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(96, 83, 150));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Medical Reports");

        btnViewMedReports.setBackground(new java.awt.Color(96, 83, 150));
        btnViewMedReports.setForeground(new java.awt.Color(255, 255, 255));
        btnViewMedReports.setLabel("View");
        btnViewMedReports.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMedReportsActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(96, 83, 150));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Doctor Records");

        jScrollPane2.setBackground(new java.awt.Color(247, 247, 247));
        jScrollPane2.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        tblDocReports.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        tblDocReports.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Doctor Visit Number", "Date"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tblDocReports.setGridColor(new java.awt.Color(247, 247, 247));
        tblDocReports.setRowHeight(20);
        tblDocReports.setSelectionBackground(new java.awt.Color(96, 83, 150));
        jScrollPane2.setViewportView(tblDocReports);

        btnViewDocRecs.setBackground(new java.awt.Color(96, 83, 150));
        btnViewDocRecs.setForeground(new java.awt.Color(255, 255, 255));
        btnViewDocRecs.setLabel("View");
        btnViewDocRecs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewDocRecsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewMedReports, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnViewDocRecs, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 694, Short.MAX_VALUE))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1))
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewMedReports, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnViewDocRecs, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(281, Short.MAX_VALUE))
        );

        add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 110, 820, 840));

        jPanel15.setBackground(new java.awt.Color(96, 83, 150));

        btn_close.setBackground(new java.awt.Color(96, 83, 150));
        btn_close.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_close.setForeground(new java.awt.Color(255, 255, 255));
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Pages/images/icons8_back_to_40px.png"))); // NOI18N
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(180, Short.MAX_VALUE)
                .addComponent(btn_close)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_close, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 0, 230, 70));

        patientLabel.setBackground(new java.awt.Color(41, 216, 95));
        patientLabel.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        patientLabel.setForeground(new java.awt.Color(96, 83, 150));
        add(patientLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, 110, 30));

        jPanel11.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 930, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 930, -1));

        jLabel15.setBackground(new java.awt.Color(41, 216, 95));
        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(96, 83, 150));
        jLabel15.setText("Medical History");
        add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 160, 40));

        jLabel16.setBackground(new java.awt.Color(41, 216, 95));
        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(96, 83, 150));
        jLabel16.setText("Patient Name");
        add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 40, 230, 30));
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewMedReportsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMedReportsActionPerformed
        // TODO add your handling code here:
        
           
        int selectedRow = tblMedicalReports.getSelectedRow();
        if(selectedRow >= 0)
        {
        MedicalReport mRepo = (MedicalReport)tblMedicalReports.getValueAt(selectedRow,0);
        CardLayout layout = (CardLayout)this.rightPanel.getLayout();
        this.rightPanel.add(new MedicalReportDisplay(this.rightPanel,mRepo ));
        layout.next(this.rightPanel);
        

        }
        else{
        JOptionPane.showMessageDialog(null, "Please select a record");
        }
        
                   
    }//GEN-LAST:event_btnViewMedReportsActionPerformed

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
      //  System.exit(0);
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        rightPanel.remove(this);
        layout.previous(rightPanel);

      
        
        
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btnViewDocRecsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewDocRecsActionPerformed
        // TODO add your handling code here:
        
       int selectedRow = tblDocReports.getSelectedRow();
        if(selectedRow >= 0)
        {
        PatientDocRecord pDoc = (PatientDocRecord) tblDocReports.getValueAt(selectedRow,0);
        CardLayout layout = (CardLayout)this.rightPanel.getLayout();
        this.rightPanel.add(new MedicalDocDisplay(this.rightPanel,pDoc,this.pat1));
        layout.next(this.rightPanel);
        

        }
        else{
        JOptionPane.showMessageDialog(null, "Please select a record");
        }
        
                   
                     
    }//GEN-LAST:event_btnViewDocRecsActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnViewDocRecs;
    private java.awt.Button btnViewMedReports;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel patientLabel;
    private javax.swing.JTable tblDocReports;
    private javax.swing.JTable tblMedicalReports;
    // End of variables declaration//GEN-END:variables
}
