/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.Airliners.Airliner;
import Business.TravelOffice.MainTravelAgency;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rohit
 */
public class AddNewAirlinerPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewAirlinerPanel
     */
    
//    Airliner airliner;
    MainTravelAgency mainTravelAgency;
    JPanel displayPanel;
    
    public AddNewAirlinerPanel(JPanel displayPanel, MainTravelAgency mainTravelAgency) {
        initComponents();
        this.displayPanel = displayPanel;
        
        warningLabel2.setForeground(Color.red);
        warningLbl.setForeground(Color.red);
        this.mainTravelAgency= mainTravelAgency;
        warningLbl.setVisible(false);
        warningLabel2.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        aircraftTypetxt = new javax.swing.JTextField();
        aircraftNametxt = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        addAirlinerBtn = new javax.swing.JButton();
        warningLbl = new javax.swing.JLabel();
        warningLabel2 = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel1.setText("<html><font size=5> <u> <b>Create New Airliner");

        jLabel2.setText("Airliner Name * :");

        jLabel3.setText("Airliner Code* :");

        jButton1.setText("<<");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        addAirlinerBtn.setText("Add");
        addAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAirlinerBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton1)
                        .addGap(145, 145, 145)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(109, 109, 109)
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(aircraftTypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(addAirlinerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(105, 105, 105)
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(aircraftNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(warningLbl)
                            .addComponent(warningLabel2))))
                .addContainerGap(185, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(aircraftNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warningLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(aircraftTypetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warningLabel2))
                .addGap(18, 18, 18)
                .addComponent(addAirlinerBtn)
                .addContainerGap(154, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAirlinerBtnActionPerformed
        
        String name = aircraftNametxt.getText();
        String code = aircraftTypetxt.getText();
        if(!airlinerNameCheck())
        {
            warningLbl.setVisible(true);
            warningLbl.setText("Only Alphanumeric names allowed");        
        
        }
//        else
//            warningLbl.setVisible(false);
//        
        if(!airlinerTypeCheck())
        {
            warningLabel2.setVisible(true);
            warningLabel2.setText("Only Alphanumeric names allowed");        
        
        }
//        else
//            warningLabel2.setVisible(false);
//        
//        
                
        
        if(mainTravelAgency.airlineNameExists(name)){
            warningLbl.setVisible(true);
            warningLbl.setText("Name already exists! Please enter unique Name.");        
        
        }
//        else{
//           warningLbl.setVisible(false);        
//        }
        if(mainTravelAgency.airlineCodeExists(code)){
            warningLabel2.setVisible(true);
            warningLabel2.setText("Code already exists! Please enter unique code.");
        
        }
//        else{
//           warningLbl.setVisible(false);        
//        
//        }
        if(name.isEmpty()){
            JOptionPane.showMessageDialog(null, "Name can't be empty");
        
        }
        
        if(code.isEmpty()){
            JOptionPane.showMessageDialog(null, "Code can't be empty");        
        }
        
        if(!mainTravelAgency.airlineCodeExists(code) && !mainTravelAgency.airlineNameExists(name)
                && airlinerNameCheck() && airlinerTypeCheck()
                
                ){
            if(code.isEmpty() || name.isEmpty()){
            
            
            }
            else{
                
                warningLbl.setVisible(false);
                warningLabel2.setVisible(false);             
                Airliner airliner = new Airliner(name, code);
                mainTravelAgency.addAirliner(airliner);
                mainTravelAgency.getMasterFlightSchedule().addAirliners(airliner);
                JOptionPane.showMessageDialog(null,"Airliner Successfully Added");
            }
        }       
    }//GEN-LAST:event_addAirlinerBtnActionPerformed

    private boolean airlinerNameCheck(){
        Pattern p = Pattern.compile("^[a-zA-Z0-9-]*$");
        Matcher m = p.matcher(aircraftNametxt.getText());
        boolean b = m.matches();
        return b;
    
    }

 
    private boolean airlinerTypeCheck(){
        Pattern p = Pattern.compile("^[a-zA-Z0-9-]*$");
        Matcher m = p.matcher(aircraftTypetxt.getText());
        boolean b = m.matches();
        return b;
    
    }
   
    
    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
        Component[] comps = this.displayPanel.getComponents();
        for(Component comp: comps){
            if(comp instanceof ManageAirlinersJPanel){
                ManageAirlinersJPanel manageAdmin = (ManageAirlinersJPanel) comp;
                manageAdmin.populate();
            }
        }      
        CardLayout layout = (CardLayout)displayPanel.getLayout();
        displayPanel.remove(this);
        layout.previous(displayPanel);


    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAirlinerBtn;
    private javax.swing.JTextField aircraftNametxt;
    private javax.swing.JTextField aircraftTypetxt;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel warningLabel2;
    private javax.swing.JLabel warningLbl;
    // End of variables declaration//GEN-END:variables
}
