/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.Airliners.Airliner;
import Business.TravelOffice.MainTravelAgency;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author rohit
 */
public class UpdateAirliner extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewAirlinerPanel
     */
    
//    Airliner airliner;
    MainTravelAgency mainTravelAgency;
    JPanel displayPanel;
    Airliner airliner;
    
    public UpdateAirliner(JPanel displayPanel, MainTravelAgency mainTravelAgency, Airliner airliner) {
        initComponents();
        this.displayPanel = displayPanel;
        
        warningLabel2.setForeground(Color.red);
        warningLbl.setForeground(Color.red);
        this.airliner = airliner;
        this.mainTravelAgency= mainTravelAgency;
        warningLbl.setVisible(false);
        warningLabel2.setVisible(false);
        saveAirlinerBtn.setEnabled(false);
        updateBtn.setEnabled(true);
        
        airlinerNametxt.setEnabled(false);
        airlinerNametxt.setText(airliner.getAirlineName());                
        airlinerCodetxt.setEnabled(false);
        airlinerCodetxt.setText(airliner.getAirlineCode());                
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        airlinerCodetxt = new javax.swing.JTextField();
        airlinerNametxt = new javax.swing.JTextField();
        backButton = new javax.swing.JButton();
        saveAirlinerBtn = new javax.swing.JButton();
        warningLbl = new javax.swing.JLabel();
        warningLabel2 = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 204));
        setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Update Airliner");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Airliner Name * :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Airliner Code* :");

        airlinerCodetxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        airlinerNametxt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        backButton.setBackground(new java.awt.Color(0, 0, 0));
        backButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(255, 0, 102));
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        saveAirlinerBtn.setBackground(new java.awt.Color(0, 0, 0));
        saveAirlinerBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        saveAirlinerBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveAirlinerBtn.setText("Save");
        saveAirlinerBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAirlinerBtnActionPerformed(evt);
            }
        });

        updateBtn.setBackground(new java.awt.Color(0, 0, 0));
        updateBtn.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        updateBtn.setForeground(new java.awt.Color(255, 255, 255));
        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(111, 111, 111)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(saveAirlinerBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(airlinerCodetxt))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(warningLbl)
                                    .addComponent(warningLabel2)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(airlinerNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(backButton)))
                .addGap(187, 187, 187))
            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(airlinerNametxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warningLbl))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(airlinerCodetxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warningLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveAirlinerBtn)
                    .addComponent(updateBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 106, Short.MAX_VALUE)
                .addComponent(backButton)
                .addGap(46, 46, 46))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveAirlinerBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveAirlinerBtnActionPerformed
        
        String name = airlinerNametxt.getText();
        String code = airlinerCodetxt.getText();
        

        // Name same, code different..
        if(name.equals(airliner.getAirlineName())
                               && airlinerTypeCheck()
                ){
        
            warningLbl.setVisible(false);
            if(!airlineCodeExists(code)){
                airliner.setAirlineCode(code);
                JOptionPane.showMessageDialog(null,"Airliner Details Updated successfully");
                saveAirlinerBtn.setEnabled(false);
                updateBtn.setEnabled(true);
                airlinerNametxt.setEnabled(false);
                airlinerCodetxt.setEnabled(false); 
            }
        }
        
        
        // Code same, name different
        if(code.equals(airliner.getAirlineCode())){
    
            warningLabel2.setVisible(false);
            if(!airlineNameExists(name) 
               && airlinerNameCheck()    
                    ){
                airliner.setAirlineName(name);
                JOptionPane.showMessageDialog(null,"Airliner Details Updated successfully");
                saveAirlinerBtn.setEnabled(false);
                updateBtn.setEnabled(true);
                airlinerNametxt.setEnabled(false);
                airlinerCodetxt.setEnabled(false);                

            }
        }
        
        if(name.isEmpty()){
            JOptionPane.showMessageDialog(null, "Name can't be empty");
        
        }
        if(code.isEmpty()){
            JOptionPane.showMessageDialog(null, "Code can't be empty");        
        }
        
// Adding if both do not exist already..
        if(!mainTravelAgency.airlineCodeExists(code) && !mainTravelAgency.airlineNameExists(name)
               && airlinerNameCheck()
                && airlinerTypeCheck()
                ){
            if(code.isEmpty() || name.isEmpty()){
            }
            else{
                warningLbl.setVisible(false);
                warningLabel2.setVisible(false);                
                airliner.setAirlineCode(code);
                airliner.setAirlineName(name);
                JOptionPane.showMessageDialog(null,"Airliner Details Updated successfully");
                saveAirlinerBtn.setEnabled(false);
                updateBtn.setEnabled(true);
                airlinerNametxt.setEnabled(false);
                airlinerCodetxt.setEnabled(false);                
            }
        }
        
        
        if(code.equals(airliner.getAirlineCode()) && name.equals(airliner.getAirlineName())){
                warningLbl.setVisible(false);
                warningLabel2.setVisible(false); 
        
        }
        
        
        
        
    }//GEN-LAST:event_saveAirlinerBtnActionPerformed

    
    
    private boolean airlineNameExists(String name){
            // If name already exists
            if(mainTravelAgency.airlineNameExists(name)){
                warningLbl.setVisible(true);
                warningLbl.setText("Name already exists! Please enter unique Name.");        
                return true;
            }
            else{
               warningLbl.setVisible(false);
               return false;
            }   
 }
    
    
    private boolean airlineCodeExists(String code){
                    // if code already exists
            if(mainTravelAgency.airlineCodeExists(code)){
                warningLabel2.setVisible(true);
                warningLabel2.setText("Code already exists! Please enter unique code.");
                return true;
            }
            else{
               warningLbl.setVisible(false);        
               return false;
            }
    }
        
      private boolean airlinerNameCheck(){
        Pattern p = Pattern.compile("^[a-zA-Z0-9-]*$");
        Matcher m = p.matcher(airlinerNametxt.getText());
        boolean b = m.matches();
                
        if(b == false)
        {
                 warningLbl.setVisible(true);
                warningLbl.setText("Only alphanumeric characters allowed");       
        
        }
        else{
                         warningLbl.setVisible(false);
        
        }
        
        return b;
    
    }

 
    private boolean airlinerTypeCheck(){
        Pattern p = Pattern.compile("^[a-zA-Z0-9-]*$");
        Matcher m = p.matcher(airlinerCodetxt.getText());
        boolean b = m.matches();
        
        if(b == false)
        {
        warningLabel2.setVisible(true);
        warningLabel2.setText("Only alphanumeric characters allowed.");       
        
        }
        else{
        warningLabel2.setVisible(false);
        
        }
        
        
      return b;
    }
     
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed



        
        Component[] comps = this.displayPanel.getComponents();
        for(Component comp: comps){
            if(comp instanceof ManageAirlinersJPanel){
                ManageAirlinersJPanel manageAdmin = (ManageAirlinersJPanel) comp;
                manageAdmin.populate();
            
            }
        
        
        }
        
        CardLayout layout = (CardLayout)displayPanel.getLayout();
        displayPanel.remove(this);
        layout.previous(displayPanel);
       
    }//GEN-LAST:event_backButtonActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        saveAirlinerBtn.setEnabled(true);
        updateBtn.setEnabled(false);
        airlinerNametxt.setEnabled(true);
        airlinerCodetxt.setEnabled(true);
    }//GEN-LAST:event_updateBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField airlinerCodetxt;
    private javax.swing.JTextField airlinerNametxt;
    private javax.swing.JButton backButton;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton saveAirlinerBtn;
    private javax.swing.JButton updateBtn;
    private javax.swing.JLabel warningLabel2;
    private javax.swing.JLabel warningLbl;
    // End of variables declaration//GEN-END:variables
}
