/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface.ManageAirliners;

import Business.Airliners.AircraftFlights;
import Business.Airliners.Airliner;
import Business.Airliners.Airplane;
import Business.Airliners.Flight;
import Business.Airliners.FlightDates;
import Business.TravelOffice.MainTravelAgency;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Locale;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import org.jdesktop.swingx.JXDatePicker;

/**
 *
 * @author rohit
 */
public class UpdateFlightSchedule extends javax.swing.JPanel {

    /**
     * Creates new form CreateNewAirlinerPanel
     */
    
//    Airliner airliner;
    MainTravelAgency mainTravelAgency;
    JPanel displayPanel;
    
    Airplane aircraft;
    AircraftFlights flight;

    
    public UpdateFlightSchedule(Airplane aircraft, AircraftFlights flight, MainTravelAgency mainTravelAgency, JPanel displayPanel) {
        initComponents();
        this.displayPanel = displayPanel;
        this.mainTravelAgency = mainTravelAgency;
        this.aircraft = aircraft;
        this.flight = flight;
        
        aircraftNameTxt.setText("<html> Aircraft Type <font size=5>"+aircraft.getName());
        AircraftCodeTxt.setText("<html> Aircraft Type <font size=5>"+aircraft.getType());
        setFieldsEnabled(false);
        setDataValues();
        saveBtn.setEnabled(false);
        updateBtn.setEnabled(true);
        updateFlightTime.setVisible(false);
        
        populate();

    }
    public void populate(){
         DefaultTableModel dtm = (DefaultTableModel)tblDirectory.getModel();
        dtm.setRowCount(0);
            for(FlightDates a : flight.getFlightDates()){
                Object[] row = new Object[dtm.getColumnCount()];
                row[0]=a;
                String time = Float.toString(a.getFlightTime());
                String[] arrOfStr = time.split("\\.");
               if(arrOfStr[1].length() == 4)
               {
                row[1] = " "+arrOfStr[0]+ " : "+ arrOfStr[1].substring(0, 2)+ " ";                   
               
               }
               else
                row[1] = arrOfStr[0]+ " : "+ arrOfStr[1]+ " ";
               row[2] = a.getArrivalTime();
               row[3] = a.getPrice();

               dtm.addRow(row);
            }
        
   
    
    
    
    
    
    }
    public void setDataValues(){
    
        flightNumTxt.setText(flight.getFlightNumber());
        originTxt.setText(flight.getOriginCity());
        destTxt.setText(flight.getDestinationCity());
    //    priceTxt.setText(Double.toString(flight.getPrice()));
        
        
        
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        destTxt = new javax.swing.JTextField();
        originTxt = new javax.swing.JTextField();
        flightNumTxt = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        saveBtn = new javax.swing.JButton();
        backBtn = new javax.swing.JButton();
        warningFlightNumberLbl = new javax.swing.JLabel();
        warningOriginLbl = new javax.swing.JLabel();
        warningDestLbl = new javax.swing.JLabel();
        warningtTckLbl = new javax.swing.JLabel();
        aircraftNameTxt = new javax.swing.JLabel();
        AircraftCodeTxt = new javax.swing.JLabel();
        updateBtn = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblDirectory = new javax.swing.JTable();
        updateFlightTime = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setPreferredSize(new java.awt.Dimension(600, 400));

        jLabel1.setText("<html><font size=5> <u> <b> Update Flight Schedule ");

        jLabel2.setText("Origin City :");

        jLabel3.setText("Destination City :");

        jLabel7.setText("Flight Number :");

        saveBtn.setText("Save");
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        backBtn.setText("<<");
        backBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backBtnActionPerformed(evt);
            }
        });

        aircraftNameTxt.setText("<html><font size = 3>");

        updateBtn.setText("Update");
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });

        tblDirectory.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Dates", "Departure Time", "Arrival Time", "Price"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(tblDirectory);

        updateFlightTime.setText("Update Flight Time");
        updateFlightTime.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateFlightTimeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(backBtn)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(81, 81, 81)
                        .addComponent(aircraftNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(224, 224, 224)
                        .addComponent(AircraftCodeTxt))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(191, 191, 191)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(103, 103, 103)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addGap(18, 18, 18)
                                        .addComponent(flightNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addGap(18, 18, 18)
                                        .addComponent(originTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(18, 18, 18)
                                        .addComponent(destTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 188, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(warningOriginLbl)
                                    .addComponent(warningDestLbl)
                                    .addComponent(warningtTckLbl)
                                    .addComponent(warningFlightNumberLbl)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(updateFlightTime, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(243, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(aircraftNameTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AircraftCodeTxt)))
                    .addComponent(backBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(43, 43, 43)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(flightNumTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warningFlightNumberLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(originTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warningOriginLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(destTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(warningDestLbl))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(warningtTckLbl)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(updateBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(updateFlightTime, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(49, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        String flightNum = flightNumTxt.getText();
        String origin = originTxt.getText();
        String dest = destTxt.getText();
     //   String priceS = priceTxt.getText();
        
        float time = 0.0F;
        double price = 0.0;
        
        
        if(!flight.getFlightNumber().equals(flightNum)){
            if(this.mainTravelAgency.getMasterFlightSchedule().flightNumberExists(flightNum))
            {
                warningFlightNumberLbl.setForeground(Color.red);
                warningFlightNumberLbl.setText("Flight number already exists!");         
            }
        }
        
        try{
    //            price = Double.parseDouble(priceTxt.getText());
            }
            catch(Exception e){
                warningtTckLbl.setVisible(true);
                warningtTckLbl.setText("Invalid price. Please enter correct number.");
            }        
        
        if(origin.length() == 0){     
            warningOriginLbl.setVisible(true);
            warningOriginLbl.setText("Origin City cannot be empty");
        
        }
        else{
            warningOriginLbl.setVisible(false);
            warningOriginLbl.setText("Origin City cannot be empty");
        }
        
        if(dest.length() == 0){
            warningDestLbl.setVisible(true);
            warningDestLbl.setText("Destination City cannot be empty");        
        
        }
        
        else{
            warningDestLbl.setVisible(false);
            warningDestLbl.setText("Origin City cannot be empty");              
        }
        
        if(origin.equals(dest)){
            warningOriginLbl.setVisible(true);
            warningOriginLbl.setText("Origin and Destination city cannot be same");              
           
        }

        
        if((origin.length() != 0) &&
            (dest.length() != 0) &&
                (price != 0) &&
                (flightNum.length() != 0) &&
                !(origin.equals(dest))
                ){

            warningDestLbl.setText("");
            warningOriginLbl.setText("");
            warningFlightNumberLbl.setText("");
            warningtTckLbl.setText("");

            this.flight.setDestinationCity(dest);
            this.flight.setOriginCity(origin);
            this.flight.setPrice(price);
            if(!this.flight.getFlightNumber().equals(flightNum)){
                this.flight.setFlightNumber(flightNum);
            }
             
            JOptionPane.showMessageDialog(null, "Successfully added!"); 
            }
    }//GEN-LAST:event_saveBtnActionPerformed
    
    private void backBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backBtnActionPerformed

        Component[] comps = this.displayPanel.getComponents();
        for(Component comp: comps){
            if(comp instanceof ViewAircraftDetails){
                ViewAircraftDetails viewAircraftDet = (ViewAircraftDetails) comp;
                viewAircraftDet.populate();            
            }
    
        }
        
        CardLayout layout = (CardLayout)displayPanel.getLayout();
        displayPanel.remove(this);
        layout.previous(displayPanel);
    }//GEN-LAST:event_backBtnActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed
        saveBtn.setEnabled(true);
        setFieldsEnabled(true);
        updateFlightTime.setVisible(true);
        
        




    }//GEN-LAST:event_updateBtnActionPerformed

    private void updateFlightTimeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateFlightTimeActionPerformed

        int selectedRow = tblDirectory.getSelectedRow();
        if(selectedRow >= 0)
        {            
            FlightDates flightDates = (FlightDates)tblDirectory.getValueAt(selectedRow, 0);
            UpdateFlightTime updateFlightTime = new UpdateFlightTime(aircraft, flight,flightDates , mainTravelAgency, this.displayPanel);
            displayPanel.add("updateFlightTime", updateFlightTime);
            CardLayout layout = (CardLayout) this.displayPanel.getLayout();
            layout.next(displayPanel);
  
        }   
        
        
        
        
        




    }//GEN-LAST:event_updateFlightTimeActionPerformed
    public static Date getNextDate(Date  curDate) {
      final Calendar calendar = Calendar.getInstance();
      calendar.setTime(curDate);
      calendar.add(Calendar.DAY_OF_YEAR, 1);
      return  calendar.getTime(); 
      

    }
   
    
    
    
    
    public void setFieldsEnabled(boolean b){
        flightNumTxt.setEnabled(b);
        originTxt.setEnabled(b);
        destTxt.setEnabled(b);
   //     priceTxt.setEnabled(b);
              
            }
    
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AircraftCodeTxt;
    private javax.swing.JLabel aircraftNameTxt;
    private javax.swing.JButton backBtn;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JTextField destTxt;
    private javax.swing.JTextField flightNumTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField originTxt;
    private javax.swing.JButton saveBtn;
    private javax.swing.JTable tblDirectory;
    private javax.swing.JButton updateBtn;
    private javax.swing.JButton updateFlightTime;
    private javax.swing.JLabel warningDestLbl;
    private javax.swing.JLabel warningFlightNumberLbl;
    private javax.swing.JLabel warningOriginLbl;
    private javax.swing.JLabel warningtTckLbl;
    // End of variables declaration//GEN-END:variables
}
