/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Pages.adminPages;

import Business.Departments.Organization;
import Business.EcoSystem;
import Business.Employees.Employee;
import Business.Enterprises.Enterprise;
import Business.Network.Network;
import Business.Role.AdminRole;
import Business.Role.HospitalAdminRole;
import Business.Role.InsuranceAdminRole;
import Business.UserAccount.UserAccount;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.Image;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Rohit
 */
public class CreateEnterprise extends javax.swing.JPanel {

    
    JPanel rightPanel;
    Network network;
    UserAccount userAccount;
    Enterprise enterprise;
    EcoSystem system;
    Image image;
    
    
    Boolean userUnique;
    
    
    /**
     * Creates new form BillingPage1
     */
    public CreateEnterprise(JPanel rightPanel,Network network, UserAccount ua, EcoSystem system) {
        this.network = network;
        this.rightPanel =rightPanel;
        this.userAccount =ua;
        this.system = system;
//        this.enterprise = enterprise;
        initComponents();
        init();
        populateEnterpriseTable();
 //       populateAdminTable();
        
    }

        public void init(){
         // Setting welcome string
         
         welcomelabel.setText("For network : "+network.getName()+" and location : "+network.getLocation());
            
            
            
            
        // Setting color of JTable
        
        
        DefaultTableCellRenderer headerRenderer = new DefaultTableCellRenderer();
        headerRenderer.setBackground(Color.white);
       // headerRenderer.set(Color.BLACK);

        for (int i = 0; i < networkEnterpriseTable.getModel().getColumnCount(); i++) {
            networkEnterpriseTable.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
           
        }
        for (int i = 0; i < adminTable.getModel().getColumnCount(); i++) {
          adminTable.getColumnModel().getColumn(i).setHeaderRenderer(headerRenderer);
           
        }
    
        // Set combo box color
        enterpriseTypeJComboBox.getEditor().getEditorComponent().setBackground(Color.white);
        populateComboBox();
        
        // Admin Panel Visibility
        addAdminPanelVisible(false);
        
    }
        
    public void addAdminPanelVisible(boolean set){
        addAdminPanel.setVisible(set);
        //.setVisible(set);    
    
    }
    
    public void populateEnterpriseTable(){
        DefaultTableModel model = (DefaultTableModel) networkEnterpriseTable.getModel();

        model.setRowCount(0);
        for (Enterprise et : network.getEnterpriseDirectory().getEnterpriseList()) {
            Object[] row = new Object[2];
            row[0] = et;
            row[1] = et.getEnterpriseType();
            model.addRow(row);
        }

    
    }

    
    public void populateAdminTable(){
       DefaultTableModel model1 = (DefaultTableModel) adminTable.getModel();

        model1.setRowCount(0);
       for (UserAccount userAccount : this.enterprise.getUserAccountDirectory().getUserAccountList())
               {

                        Object[] row = new Object[5];
                    
                        row[0] = this.enterprise.getName();
                        row[1] = userAccount.getEmployee().getName();
                        row[2] = userAccount.getEmployee().getId();
                        row[3] = userAccount;
                        row[4] = userAccount.getPassword();

                        model1.addRow(row);
                    
          }
        
        
       
                
    
    }   
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel15 = new javax.swing.JPanel();
        btn_close = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        addNetBtn = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        enterpriseName = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        welcomelabel = new javax.swing.JLabel();
        enterpriseTypeJComboBox = new javax.swing.JComboBox();
        addAdmin = new javax.swing.JButton();
        addAdminPanel = new javax.swing.JPanel();
        adminLabel = new javax.swing.JLabel();
        adminName = new javax.swing.JTextField();
        adminUser = new javax.swing.JLabel();
        adminusername = new javax.swing.JTextField();
        adminPasswordLabel = new javax.swing.JLabel();
        addAdminBtn = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        inPhotoBtn1 = new javax.swing.JButton();
        jPhoto1 = new javax.swing.JLabel();
        adminpassword = new javax.swing.JPasswordField();
        jScrollPane3 = new javax.swing.JScrollPane();
        adminTable = new javax.swing.JTable();
        jButton5 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        networkEnterpriseTable = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel15.setBackground(new java.awt.Color(96, 83, 150));

        btn_close.setBackground(new java.awt.Color(96, 83, 150));
        btn_close.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btn_close.setForeground(new java.awt.Color(255, 255, 255));
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Pages/images/icons8_back_to_40px.png"))); // NOI18N
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addContainerGap(172, Short.MAX_VALUE)
                .addComponent(btn_close)
                .addContainerGap())
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_close, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        jPanel11.setBackground(new java.awt.Color(232, 201, 232));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 11, Short.MAX_VALUE)
        );

        addNetBtn.setBackground(new java.awt.Color(247, 247, 247));
        addNetBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Images/icons8_add_40px_1.png"))); // NOI18N
        addNetBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNetBtnActionPerformed(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(96, 83, 150));
        jLabel9.setText("Add Enterprise?");

        jLabel8.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(96, 83, 150));
        jLabel8.setText("Enterprise Type");

        jSeparator5.setForeground(new java.awt.Color(255, 255, 255));

        enterpriseName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        enterpriseName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        enterpriseName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        enterpriseName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                enterpriseNameMouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(96, 83, 150));
        jLabel4.setText("Enterprise Name");

        jSeparator4.setForeground(new java.awt.Color(255, 255, 255));

        welcomelabel.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        welcomelabel.setForeground(new java.awt.Color(96, 83, 150));
        welcomelabel.setText("Hello");

        enterpriseTypeJComboBox.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        addAdmin.setBackground(new java.awt.Color(247, 247, 247));
        addAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Pages/images/icons8_add_user_group_woman_man_40px_3.png"))); // NOI18N
        addAdmin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdminActionPerformed(evt);
            }
        });

        addAdminPanel.setBackground(new java.awt.Color(255, 255, 255));

        adminLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        adminLabel.setForeground(new java.awt.Color(96, 83, 150));
        adminLabel.setText("Admin Name");

        adminName.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        adminName.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        adminName.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        adminName.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminNameMouseClicked(evt);
            }
        });

        adminUser.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        adminUser.setForeground(new java.awt.Color(96, 83, 150));
        adminUser.setText("Username");

        adminusername.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        adminusername.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        adminusername.setDisabledTextColor(new java.awt.Color(204, 204, 204));
        adminusername.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminusernameMouseClicked(evt);
            }
        });
        adminusername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminusernameActionPerformed(evt);
            }
        });

        adminPasswordLabel.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        adminPasswordLabel.setForeground(new java.awt.Color(96, 83, 150));
        adminPasswordLabel.setText("Password");

        addAdminBtn.setBackground(new java.awt.Color(247, 247, 247));
        addAdminBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/main/Images/icons8_add_40px_1.png"))); // NOI18N
        addAdminBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addAdminBtnActionPerformed(evt);
            }
        });

        inPhotoBtn1.setBackground(new java.awt.Color(247, 247, 247));
        inPhotoBtn1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Pages/images/icons8-client_management.png"))); // NOI18N
        inPhotoBtn1.setText("Upload Photo");
        inPhotoBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inPhotoBtn1ActionPerformed(evt);
            }
        });

        adminpassword.setFont(new java.awt.Font("Century Gothic", 0, 12)); // NOI18N
        adminpassword.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jScrollPane3.setBackground(new java.awt.Color(247, 247, 247));
        jScrollPane3.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        adminTable.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        adminTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "Enterprise", "Name", "Id", "User Name", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        adminTable.setGridColor(new java.awt.Color(247, 247, 247));
        adminTable.setRowHeight(20);
        adminTable.setSelectionBackground(new java.awt.Color(96, 83, 150));
        jScrollPane3.setViewportView(adminTable);

        jButton5.setBackground(new java.awt.Color(247, 247, 247));
        jButton5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Pages/images/icons8_minus_40px_2.png"))); // NOI18N
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(96, 83, 150));
        jLabel7.setText("Enterprises");

        javax.swing.GroupLayout addAdminPanelLayout = new javax.swing.GroupLayout(addAdminPanel);
        addAdminPanel.setLayout(addAdminPanelLayout);
        addAdminPanelLayout.setHorizontalGroup(
            addAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAdminPanelLayout.createSequentialGroup()
                .addGroup(addAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addAdminPanelLayout.createSequentialGroup()
                        .addGap(96, 96, 96)
                        .addComponent(jLabel1))
                    .addGroup(addAdminPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jPhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addAdminPanelLayout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addGroup(addAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addAdminPanelLayout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addComponent(inPhotoBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(addAdminBtn))
                            .addGroup(addAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, addAdminPanelLayout.createSequentialGroup()
                                    .addGroup(addAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(adminLabel)
                                        .addComponent(adminUser)
                                        .addComponent(adminPasswordLabel))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(addAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(adminName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(adminusername, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(adminpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(addAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addAdminPanelLayout.setVerticalGroup(
            addAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addAdminPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addAdminPanelLayout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(addAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adminName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(adminLabel))
                        .addGap(18, 18, 18)
                        .addGroup(addAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adminUser)
                            .addComponent(adminusername, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(addAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(adminPasswordLabel)
                            .addComponent(adminpassword, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(addAdminPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(addAdminBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inPhotoBtn1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(addAdminPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton5)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPhoto1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setBackground(new java.awt.Color(247, 247, 247));
        jScrollPane1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));

        networkEnterpriseTable.setFont(new java.awt.Font("Segoe UI", 0, 11)); // NOI18N
        networkEnterpriseTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null}
            },
            new String [] {
                "Name", "Type"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        networkEnterpriseTable.setGridColor(new java.awt.Color(247, 247, 247));
        networkEnterpriseTable.setRowHeight(20);
        networkEnterpriseTable.setSelectionBackground(new java.awt.Color(96, 83, 150));
        jScrollPane1.setViewportView(networkEnterpriseTable);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(96, 83, 150));
        jLabel10.setText("Enterprises");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(enterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addNetBtn)
                    .addComponent(enterpriseTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(191, 191, 191)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 414, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addAdmin)
                .addContainerGap(93, Short.MAX_VALUE))
            .addComponent(jPanel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(welcomelabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(addAdminPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(welcomelabel)))
                .addGap(16, 16, 16)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addComponent(jLabel4)
                        .addGap(16, 16, 16)
                        .addComponent(enterpriseName, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jSeparator4, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, 0)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(enterpriseTypeJComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(jSeparator5, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(addNetBtn))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(addAdmin)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addAdminPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        
        
        Component[] comps = this.rightPanel.getComponents();
        for(Component comp: comps){
            if(comp instanceof SysAdmin_WorkArea){
                SysAdmin_WorkArea manageAdmin = (SysAdmin_WorkArea) comp;
                manageAdmin.populateNetworkTable();
                manageAdmin.init();
            
            }
        
        
        }
        
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        rightPanel.remove(this);
        layout.previous(rightPanel);
        
        

        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
        
    }//GEN-LAST:event_btn_closeMouseClicked
    
    private void populateComboBox() {
        enterpriseTypeJComboBox.removeAllItems();

       // for (Enterprise.EnterpriseType type : Enterprise.EnterpriseType.values()) {
            enterpriseTypeJComboBox.addItem(Enterprise.EnterpriseType.Hospital);
            enterpriseTypeJComboBox.addItem(Enterprise.EnterpriseType.Insurance);
//            enterpriseTypeJComboBox.addItem(type);
            
        //}

    }
    
    private void addNetBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNetBtnActionPerformed
        // TODO add your handling code here:


        String name = enterpriseName.getText();
        Enterprise.EnterpriseType selectedType = (Enterprise.EnterpriseType) enterpriseTypeJComboBox.getSelectedItem();
        name = name.trim();
       
         if (name.isEmpty()){
         
             JOptionPane.showMessageDialog(null, "Name is empty");
            return;
         
         
         }
        System.out.println(""+selectedType);
        
        if(name.equals("")){
        JOptionPane.showMessageDialog(null, "Please enter enterprise name");
        return;
        }
        if(network.checkEnterpriseNameUnique(name)){
            Enterprise enterprise = network.getEnterpriseDirectory().createAndAddEnterprise(name, selectedType);
            populateEnterpriseTable();
            }
        else {
            JOptionPane.showMessageDialog(null, "Enterprise with the name already exists!");
        }
    }//GEN-LAST:event_addNetBtnActionPerformed

    private void enterpriseNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_enterpriseNameMouseClicked
        // TODO add your handling code here:
        //    jTextField1.setText("");
    }//GEN-LAST:event_enterpriseNameMouseClicked

    private void addAdminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdminActionPerformed
        // TODO add your handling code here:
        int selectedRow = networkEnterpriseTable.getSelectedRow();
        if(selectedRow >= 0)
        {

            addAdminPanel.setVisible(true);
            Enterprise et  = (Enterprise) networkEnterpriseTable.getValueAt(selectedRow, 0);
            this.enterprise = et;
            
            jLabel7.setText("Enterprise : "+et.getName()+ " Type : "+et.getEnterpriseType());
            populateAdminTable();
        

        }
        





        
        

    }//GEN-LAST:event_addAdminActionPerformed

    private void adminNameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminNameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_adminNameMouseClicked

    private void adminusernameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminusernameMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_adminusernameMouseClicked

    private void addAdminBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addAdminBtnActionPerformed
        String username = adminusername.getText();
        String password = String.valueOf(adminpassword.getPassword());
        String name = adminName.getText();
        name = name.trim();
       
         if (name.isEmpty()){
            JOptionPane.showMessageDialog(null, "Name is empty");
            return;
         }
        
        // Validations
           userUnique = true;
           userUniqueValidation();
           if (userUnique == false){
           JOptionPane.showMessageDialog(null, "Username should be unique. UserName is already in use.");
                  return;}
                  
                  
      
            if (usernamePatternCorrect()==false){
                        adminUser.setForeground (Color.red);
                        adminusername.setBorder(BorderFactory.createLineBorder(Color.RED));
                        JOptionPane.showMessageDialog(null, "Username should be in the format of xx_xx@xx.xx");
                        return;
               } else{
                        adminUser.setForeground (Color.BLACK);
                        adminusername.setBorder(BorderFactory.createLineBorder(Color.black));
                     }
            if (passwordPatternCorrect()==false){
                        adminPasswordLabel.setForeground (Color.red);
                        adminpassword.setBorder(BorderFactory.createLineBorder(Color.RED));
                        JOptionPane.showMessageDialog(null, "Password should be at least 6 digits and contain at least one upper case letter, one lower case letter, one digit and one special character $, *, # or &.");
                        return;
            }else{
                        adminPasswordLabel.setForeground (Color.BLACK);
                        adminpassword.setBorder(BorderFactory.createLineBorder(Color.black));
            }

        
        Employee employee = this.enterprise.getEmployeeDirectory().createEmployee(name);
        employee.setEnterprise(enterprise);
        if (image != null)
        {
            
            employee.setPicture(image);
        
        }
        
        // Adding to lists..
        
     //   this.system.getEmployeeDirectory().getEmployeeList().add(employee);
     //    this.enterprise.getEmployeeDirectory().getEmployeeList().add(employee);
        
        if(enterprise.getEnterpriseType() == Enterprise.EnterpriseType.Hospital){
                // Create account Within the enterprise
                UserAccount account = this.enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new HospitalAdminRole());
                // Create account  Within the ecosystem
       //         this.system.getUserAccountDirectory().createUserAccount(username, password, employee, new HospitalAdminRole());
        }
        else if(enterprise.getEnterpriseType() == Enterprise.EnterpriseType.Insurance){
                // Create account Within the enterprise
                UserAccount account = this.enterprise.getUserAccountDirectory().createUserAccount(username, password, employee, new InsuranceAdminRole());
                // Create account  Within the ecosystem
       //         this.system.getUserAccountDirectory().createUserAccount(username, password, employee, new InsuranceAdminRole());
        }
        JOptionPane.showMessageDialog(null, "User Created");
      
        populateEnterpriseTable();
        
        populateAdminTable();

      
    }//GEN-LAST:event_addAdminBtnActionPerformed
      private boolean usernamePatternCorrect(){
        Pattern p=Pattern.compile("^[a-zA-Z0-9]+_[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");
        Matcher m=p.matcher(adminusername.getText());
        boolean b=m.matches();
        return b;
    }
    
     private boolean passwordPatternCorrect(){
        Pattern p1;
        p1 = Pattern.compile("^(?=.*?[A-Z])(?=.*?[a-z])(?=.*?[0-9])(?=.*?[#?!@$%^&*-]).{6,}$");
        Matcher m1=p1.matcher(String.valueOf(adminpassword.getPassword()));
        boolean b1=m1.matches();
        return b1;
    }
    private void adminusernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminusernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adminusernameActionPerformed

    private void inPhotoBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inPhotoBtn1ActionPerformed
        // Code to upload Image: Reference - Stackoverflow.com

        JFileChooser chooser = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter(
            "JPG & PNG Images", "jpg","png");
        chooser.setFileFilter(filter);
        int returnVal = chooser.showOpenDialog(CreateEnterprise.this);
        if(returnVal == JFileChooser.APPROVE_OPTION) {
            System.out.println("You chose to open this file: " +
                chooser.getSelectedFile().getName());}

        //photoPath = chooser.getSelectedFile().getPath();

        ImageIcon icon = new ImageIcon(chooser.getSelectedFile().getPath());
        image = icon.getImage();
        Image newimg = image.getScaledInstance(70,70,Image.SCALE_SMOOTH);
        ImageIcon icon2 = new ImageIcon(newimg);

        jPhoto1.setIcon(icon2);

    }//GEN-LAST:event_inPhotoBtn1ActionPerformed

    
    void userUniqueValidation(){
        String username = adminusername.getText();
        
          for(UserAccount ua : this.enterprise.getUserAccountDirectory().getUserAccountList()){
            if (ua!= null){
            if(ua.getUsername().equals(username)){
                 userUnique = false;
            return;}
            }
      }
      for(UserAccount ua : this.system.getUserAccountDirectory().getUserAccountList()){
            if (ua!= null){;
            if(ua.getUsername().equals(username)){
                  userUnique = false;
            return;}
            }
      }    
      
       
       for(Network net : system.getNetworkList()){
            for(Enterprise e : net.getEnterpriseDirectory().getEnterpriseList()){
                
            for(UserAccount ua : e.getUserAccountDirectory().getUserAccountList()){
            if (ua!= null){
            if(ua.getUsername().equals(username)){
                  userUnique = false;
            return;}
            }
            }
            
            for(Organization org :e.getOrganizationDirectory().getOrganizationList()){
                
                for(UserAccount ua1 : org.getUserAccountDirectory().getUserAccountList()){
                
                if(ua1.getUsername().equals(username)){
                  userUnique = false;
                  return;}
            
       
                      }
             
        }
        
       }
       }
       
       // Check if this user exists in Patient Directory
       
            if (system.getPatientDirectory().checkIfUsernameIsUnique(" ") == false){
                  userUnique = false;
                  return;
            }
        
    }
    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        int selectedRow = adminTable.getSelectedRow();
        if(selectedRow>=0){
            int selectionButton = JOptionPane.YES_NO_OPTION;
            int selectionResult = JOptionPane.showConfirmDialog(null, "Are you sure to delete??","Warning",selectionButton);
            if(selectionResult == JOptionPane.YES_OPTION){
                UserAccount airliner = (UserAccount)adminTable.getValueAt(selectedRow, 3);
                Employee e = airliner.getEmployee();
                this.system.getEmployeeDirectory().getEmployeeList().remove(airliner);//  mainTravelAgency.deleteAirline(airliner);
                this.enterprise.getEmployeeDirectory().getEmployeeList().remove(airliner); // createUserAccount(username, password, employee, new AdminRole());
                
                this.system.getUserAccountDirectory().getUserAccountList().remove(airliner);//  mainTravelAgency.deleteAirline(airliner);
                this.enterprise.getUserAccountDirectory().getUserAccountList().remove(airliner); // createUserAccount(username, password, employee, new AdminRole());
                
                
                populateAdminTable();
            }
        }else{
            JOptionPane.showMessageDialog(null, "Please make a selection first.");
        }
    }//GEN-LAST:event_jButton5ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addAdmin;
    private javax.swing.JButton addAdminBtn;
    private javax.swing.JPanel addAdminPanel;
    private javax.swing.JButton addNetBtn;
    private javax.swing.JLabel adminLabel;
    private javax.swing.JTextField adminName;
    private javax.swing.JLabel adminPasswordLabel;
    private javax.swing.JTable adminTable;
    private javax.swing.JLabel adminUser;
    private javax.swing.JPasswordField adminpassword;
    private javax.swing.JTextField adminusername;
    private javax.swing.JLabel btn_close;
    private javax.swing.JTextField enterpriseName;
    private javax.swing.JComboBox enterpriseTypeJComboBox;
    private javax.swing.JButton inPhotoBtn1;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JLabel jPhoto1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable networkEnterpriseTable;
    private javax.swing.JLabel welcomelabel;
    // End of variables declaration//GEN-END:variables
}
