/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UserInterface;

import Business.Users.Admin;
import Business.Users.Customer;
import Business.Users.Supplier;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.border.LineBorder;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author AEDSpring2019
 */
public class AdminCreateScreen extends javax.swing.JPanel {

    /**
     * Creates new form AdminScreen
     */
    private JPanel panelRight;
    private Admin admin;
 //   private StringBuilder warnMsg;
    
    public AdminCreateScreen(JPanel panelRight, Admin admin) {
        initComponents();
        initRadio();
        this.panelRight = panelRight;
        this.admin = admin;
        txtRePword.setBorder(new LineBorder(Color.black));
        jLabel3.setForeground(Color.black); 
        txtPword.setBorder(new LineBorder(Color.black));
        jLabel2.setForeground(Color.black); 
        txtUser.setBorder(new LineBorder(Color.black));
        jLabel1.setForeground(Color.black);    
    //    warnMsg = new StringBuilder();
        warnLabel.setVisible(false);
        
    }

    
    private void initRadio(){
        buttonGroup1.add(radioCustomer);        
        buttonGroup1.add(radioSupplier);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        btnCreate = new javax.swing.JButton();
        txtUser = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        radioCustomer = new javax.swing.JRadioButton();
        radioSupplier = new javax.swing.JRadioButton();
        btnBack = new javax.swing.JButton();
        txtPword = new javax.swing.JPasswordField();
        txtRePword = new javax.swing.JPasswordField();
        warnLabel = new javax.swing.JLabel();
        userLabel = new javax.swing.JLabel();
        pwdLabel = new javax.swing.JLabel();
        rePwdLabel = new javax.swing.JLabel();
        radioLabel = new javax.swing.JLabel();

        btnCreate.setText("Create");
        btnCreate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCreateActionPerformed(evt);
            }
        });

        jLabel1.setText("username:");

        jLabel2.setText("password:");

        jLabel3.setText("re-enter password :");

        radioCustomer.setText("Customer");
        radioCustomer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                radioCustomerActionPerformed(evt);
            }
        });

        radioSupplier.setText("Supplier");

        btnBack.setText("< BACK");
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });

        userLabel.setForeground(new java.awt.Color(255, 0, 51));

        pwdLabel.setForeground(new java.awt.Color(255, 0, 51));

        rePwdLabel.setForeground(new java.awt.Color(255, 0, 51));

        radioLabel.setForeground(new java.awt.Color(255, 0, 51));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(btnBack)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(warnLabel)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtUser, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addComponent(btnCreate, javax.swing.GroupLayout.DEFAULT_SIZE, 173, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(35, 35, 35)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(radioSupplier)
                                    .addComponent(radioCustomer)))
                            .addComponent(txtPword)
                            .addComponent(txtRePword))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(userLabel)
                            .addComponent(pwdLabel)
                            .addComponent(rePwdLabel)
                            .addComponent(radioLabel))))
                .addContainerGap(71, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBack)
                    .addComponent(warnLabel))
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(userLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtPword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(pwdLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtRePword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rePwdLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(radioCustomer)
                    .addComponent(radioLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(radioSupplier)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnCreate)
                .addContainerGap(43, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnCreateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCreateActionPerformed
        if(!usernamePatternCorrect()){
//            txtUser.setText("");
            txtUser.setBorder(new LineBorder(Color.red));
            jLabel1.setForeground(Color.red);
            userLabel.setVisible(true);
            userLabel.setText("<html> Username not in correct format. correct format: abc_de@fgh.com <br>");
        }
        else if(usernamePatternCorrect()) {
            txtUser.setBorder(new LineBorder(Color.black));
            jLabel1.setForeground(Color.black);
            userLabel.setVisible(false);

            warnLabel.setVisible(false);
            warnLabel.setForeground(Color.red);
            warnLabel.setText("");            
            
            
            
        }
        if(!pwdPatternCorrect()){
//            txtPword.setText("");
            txtPword.setBorder(new LineBorder(Color.red));
            jLabel2.setForeground(Color.red);        
            pwdLabel.setVisible(true);
            pwdLabel.setText("Password acceptable format: min. 6, one small, one capital letter, one special character and one number.");
        }
        else if(pwdPatternCorrect()) {
            txtPword.setBorder(new LineBorder(Color.black));
            jLabel2.setForeground(Color.black);        
            
            pwdLabel.setVisible(false);
            


        }
        if(!repwdCorrect()){

            txtRePword.setBorder(new LineBorder(Color.red));
            jLabel3.setForeground(Color.red);
            rePwdLabel.setVisible(true);
            rePwdLabel.setText("Retype password and password are different. <br>");        
        }
        else if (repwdCorrect())
                {
            txtRePword.setBorder(new LineBorder(Color.black));
            jLabel3.setForeground(Color.black);        
            rePwdLabel.setText("");        
        }
        if(!isTypeSelected())
        {
    //        JOptionPane.showMessageDialog(null, "Please select User-Type");    
            radioLabel.setText("Please select user type.");            
        }
        else if(isTypeSelected()){
            radioLabel.setText(""); 
        
        }
        
        
        
        if(usernamePatternCorrect() && pwdPatternCorrect() && repwdCorrect() && isTypeSelected())
        {
            String userName =    txtUser.getText();
            String pwd = txtPword.getText();
            if(radioCustomer.isSelected())
            {
                 Date dt = new Date();
                 Customer c = new Customer(pwd, userName, dt);
                 admin.custDir.getCustomerList().add(c);
                 JOptionPane.showMessageDialog(null, "Successfully Created Customer User");            
                 txtReset();

            }
            if(radioSupplier.isSelected())
            {
                 Supplier s = new Supplier(pwd, userName);
                 admin.suppDir.getSupplierList().add(s);
                 JOptionPane.showMessageDialog(null, "Successfully Created Supplier User"); 
                 txtReset();
            }
            
        }
        
    }//GEN-LAST:event_btnCreateActionPerformed


    private void txtReset(){
                 txtUser.setText("");
                 txtPword.setText("");
                 txtRePword.setText("");
    
    }






    // Is Type selected method

    
    private boolean isTypeSelected(){
        
        if(radioSupplier.isSelected() || radioCustomer.isSelected()){
            return true;
            
            
        }
        else 
            return false;
    
    }
//    +[A-Z]{1,}[0-9]{1,}[$*#&]{1,}
    
    // Username pattern correct method
    
    private boolean usernamePatternCorrect(){
        Pattern p = Pattern.compile("^[a-zA-Z0-9]+_[a-zA-Z0-9]+@[a-zA-Z0-9]+.[a-zA-Z0-9]+$");
        Matcher m = p.matcher(txtUser.getText());
        boolean b = m.matches();
        return b;
    
    }






    // Password pattern correct? method
    
    private boolean pwdPatternCorrect(){
        Pattern p = Pattern.compile("((?=.*\\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[@#$%]).{6,})"); 
        Matcher m = p.matcher(txtPword.getText());
        boolean b = m.matches();
        return b;
    
    } 
    

    // Re-Password check correct? method
    
    private boolean repwdCorrect(){
        String repwd = txtRePword.getText();
        String pwd = txtPword.getText();
        return repwd.equals(pwd);
    
    }        
    
    
    
    
    private void radioCustomerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_radioCustomerActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_radioCustomerActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        
        Component[] comps = this.panelRight.getComponents();
        for(Component comp: comps){
            if(comp instanceof AdminMainScreen){
                AdminMainScreen manageAdmin = (AdminMainScreen) comp;
                manageAdmin.customerPopulate();
                manageAdmin.populate();
            
            }
        
        
        }
        
        CardLayout layout = (CardLayout)panelRight.getLayout();
        panelRight.remove(this);
        layout.previous(panelRight);
        
        

        
        
        
    }//GEN-LAST:event_btnBackActionPerformed

    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCreate;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel pwdLabel;
    private javax.swing.JRadioButton radioCustomer;
    private javax.swing.JLabel radioLabel;
    private javax.swing.JRadioButton radioSupplier;
    private javax.swing.JLabel rePwdLabel;
    private javax.swing.JPasswordField txtPword;
    private javax.swing.JPasswordField txtRePword;
    private javax.swing.JTextField txtUser;
    private javax.swing.JLabel userLabel;
    private javax.swing.JLabel warnLabel;
    // End of variables declaration//GEN-END:variables
}
