/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package UI_Pages.InsuranceEnterprise.Agent;
import Business.Customer.Patient;
import Business.Database.DB4OUtil;
import Business.Departments.Organization;
import Business.EcoSystem;
import Business.Enterprises.Enterprise;
import Business.UserAccount.UserAccount;
import Business.WorkQueue.BuyInsuranceWorkRequest;
import UI_Pages.adminPages.SysAdmin_WorkArea;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.Format;
import java.text.SimpleDateFormat;
import javafx.stage.FileChooser;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
/**
 *
 * @author 
 */

  
    public class InsuranceAgentProcess extends javax.swing.JPanel {
      JPanel rightPanel;
      BuyInsuranceWorkRequest bReq;
      EcoSystem business;
      DB4OUtil dB4OUtil;

    /**
     * Creates new form AgentJPanel
     */
    public InsuranceAgentProcess(JPanel rightPanel,EcoSystem business,BuyInsuranceWorkRequest bReq,DB4OUtil dB4OUtil) {
        initComponents();
        this.rightPanel =  rightPanel;
        this.bReq = bReq;
        this.business = business;
        this.dB4OUtil = dB4OUtil;
        
        fillScreen();
        
        
         //Populate AWT Choices/combobox 
        
      //  cBoxMedicalHistory.addItem("Diabetes");
      //  cBoxMedicalHistory.addItem("Heart Ailment");
      //  cBoxMedicalHistory.addItem("Any other preexisting condition");
      //  cBoxMedicalHistory.select(0);
        
//        //Choice 2
//        
//        choice2.addItem("None");
//        choice2.select(0);
//      
//        //choice 3
//        
//        choice3.addItem("Everyone on project");
//        choice3.addItem("Team A");
//        choice3.addItem("Team B");
//        choice3.select(0);
    }
    
    
    void fillScreen(){
        
        
    Format f = new SimpleDateFormat("MM/dd/yy");
    
    Patient pat = bReq.getPatient();
    txtFileNo.setText(bReq.getInsReqNo());
    txtFirstName.setText(pat.getfName());
    txtLastName.setText(pat.getLastName());
    //txtAddress.setText(pat.get)
  
    String strDate = f.format(pat.getDob());
    txtDOB.setText(strDate);
    if (pat.getMobno() == null)
        txtMobileNo.setText(" ");
    else
        txtMobileNo.setText(String.valueOf(pat.getMobno()));
    
    
    txtPlan.setText(pat.getPlanType());
    String str = pat.getGender();
    rBtnMale.setSelected(false);
    rBtnFemale.setSelected(false);
    
    if (str == "Male"){
    rBtnMale.setSelected(true);
   
    }
    else
    {
    rBtnFemale.setSelected(true); 

    }
  
   
    String s1 = " ";
    int count1 = 0;
    for (String s : pat.getCheckBoxHealth()){
        if (s!=null){
            count1 = count1 + 1;;
        if (count1 == 1)
            s1 = s;
        else
            s1 = s1 +  " , " + s;
        
        
    }
    }
    txtHistory.setText(s1);
    
    txtResult.setText(bReq.getTestResult());
    
    if (bReq.getTestResult() == " " || bReq.getTestResult() == null )
        btnSendAth.setEnabled(false);
    else
        btnSendAth.setEnabled(true);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtDOB = new javax.swing.JTextField();
        txtMobileNo = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        txtPlan = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        txtLastName = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        rBtnMale = new javax.swing.JRadioButton();
        rBtnFemale = new javax.swing.JRadioButton();
        jLabel25 = new javax.swing.JLabel();
        txtResult = new javax.swing.JTextField();
        txtHistory = new javax.swing.JTextField();
        txtFileNo = new javax.swing.JLabel();
        jPanel15 = new javax.swing.JPanel();
        btn_close = new javax.swing.JLabel();
        btnSendAth = new java.awt.Button();
        jPanel11 = new javax.swing.JPanel();
        txtcustomerName = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(16, 190, 121)));
        jPanel4.setForeground(new java.awt.Color(16, 190, 121));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(12, 115, 101));
        jLabel8.setText("First Name");

        txtFirstName.setEditable(false);
        txtFirstName.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                txtFirstNameComponentMoved(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(12, 115, 101));
        jLabel11.setText("Date Of Birth");

        txtDOB.setEditable(false);

        txtMobileNo.setEditable(false);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(12, 115, 101));
        jLabel13.setText("Plan");

        txtPlan.setEditable(false);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(12, 115, 101));
        jLabel21.setText("History");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(12, 115, 101));
        jLabel22.setText("Last Name");

        txtLastName.setEditable(false);

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(12, 115, 101));
        jLabel23.setText("Mobile");

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(12, 115, 101));
        jLabel24.setText("Gender");

        rBtnMale.setBackground(new java.awt.Color(255, 255, 255));
        rBtnMale.setText("Male");
        rBtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rBtnMaleActionPerformed(evt);
            }
        });

        rBtnFemale.setBackground(new java.awt.Color(255, 255, 255));
        rBtnFemale.setText("Female");

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(12, 115, 101));
        jLabel25.setText("Test Result");

        txtResult.setEditable(false);

        txtHistory.setEditable(false);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel21)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtDOB, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
                                .addComponent(txtFirstName)
                                .addComponent(txtMobileNo)
                                .addComponent(txtPlan)
                                .addComponent(txtResult))
                            .addComponent(txtHistory, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(202, 202, 202))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(206, 206, 206)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(rBtnMale)
                                .addGap(18, 18, 18)
                                .addComponent(rBtnFemale)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(rBtnMale, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rBtnFemale, javax.swing.GroupLayout.Alignment.TRAILING))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel23, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(txtMobileNo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtPlan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel21, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtHistory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtResult, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(69, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDOB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(199, 199, 199))
        );

        add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 140, 680, 290));

        txtFileNo.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        txtFileNo.setForeground(new java.awt.Color(12, 115, 101));
        add(txtFileNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 90, 140, 41));

        jPanel15.setBackground(new java.awt.Color(12, 115, 101));

        btn_close.setBackground(new java.awt.Color(96, 83, 150));
        btn_close.setFont(new java.awt.Font("Segoe UI", 1, 8)); // NOI18N
        btn_close.setForeground(new java.awt.Color(255, 255, 255));
        btn_close.setIcon(new javax.swing.ImageIcon(getClass().getResource("/UI_Pages/images/icons8_previous_48px.png"))); // NOI18N
        btn_close.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_closeMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel15Layout = new javax.swing.GroupLayout(jPanel15);
        jPanel15.setLayout(jPanel15Layout);
        jPanel15Layout.setHorizontalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel15Layout.createSequentialGroup()
                .addGap(0, 174, Short.MAX_VALUE)
                .addComponent(btn_close, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel15Layout.setVerticalGroup(
            jPanel15Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(btn_close, javax.swing.GroupLayout.DEFAULT_SIZE, 70, Short.MAX_VALUE)
        );

        add(jPanel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 0, 230, 70));

        btnSendAth.setBackground(new java.awt.Color(16, 190, 121));
        btnSendAth.setForeground(new java.awt.Color(255, 255, 255));
        btnSendAth.setLabel("Send for Authorization");
        btnSendAth.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSendAthActionPerformed(evt);
            }
        });
        add(btnSendAth, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 450, 170, 40));

        jPanel11.setBackground(new java.awt.Color(16, 190, 121));

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 880, Short.MAX_VALUE)
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 80, 880, -1));

        txtcustomerName.setBackground(new java.awt.Color(41, 216, 95));
        txtcustomerName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtcustomerName.setForeground(new java.awt.Color(12, 115, 101));
        add(txtcustomerName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 30, 190, 30));

        jLabel14.setBackground(new java.awt.Color(41, 216, 95));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(12, 115, 101));
        jLabel14.setText("Insurance Request Details");
        add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 30, 260, 30));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(12, 115, 101));
        jLabel9.setText("File Number : ");
        add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 90, 130, 41));
    }// </editor-fold>//GEN-END:initComponents

    private void rBtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rBtnMaleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rBtnMaleActionPerformed

    private void btn_closeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_closeMouseClicked
        // TODO add your handling code here:
        //System.exit(0);
        
           
                Component[] comps = this.rightPanel.getComponents();
        for(Component comp: comps){
            if(comp instanceof InsuranceAgentDashboard){
                InsuranceAgentDashboard insDash = (InsuranceAgentDashboard) comp;
                insDash.populateInsuranceTable();
                //manageAdmin.init();
            }
        }
        
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        rightPanel.remove(this);
        layout.previous(rightPanel);
 
    }//GEN-LAST:event_btn_closeMouseClicked

    private void btnSendAthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSendAthActionPerformed
        // TODO add your handling code here:
        bReq.setStatus("In Process");
        
        dB4OUtil.storeSystem(business);
           
                Component[] comps = this.rightPanel.getComponents();
           for(Component comp: comps){
            if(comp instanceof InsuranceAgentDashboard){
                InsuranceAgentDashboard insDash = (InsuranceAgentDashboard) comp;
                insDash.populateInsuranceTable();
                //manageAdmin.init();
            }
        }
        
        CardLayout layout = (CardLayout)rightPanel.getLayout();
        rightPanel.remove(this);
        layout.previous(rightPanel);
    }//GEN-LAST:event_btnSendAthActionPerformed

    private void txtFirstNameComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_txtFirstNameComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_txtFirstNameComponentMoved


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button btnSendAth;
    private javax.swing.JLabel btn_close;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel15;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton rBtnFemale;
    private javax.swing.JRadioButton rBtnMale;
    private javax.swing.JTextField txtDOB;
    private javax.swing.JLabel txtFileNo;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtHistory;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JTextField txtMobileNo;
    private javax.swing.JTextField txtPlan;
    private javax.swing.JTextField txtResult;
    private javax.swing.JLabel txtcustomerName;
    // End of variables declaration//GEN-END:variables
//    
//    private java.awt.Choice choice2;
//    private java.awt.Choice choice3;
}
